IF OBJECT_ID('dbo.VALOR_DOLAR_PARALELO') is not null 
	drop table VALOR_DOLAR_PARALELO
go
CREATE TABLE VALOR_DOLAR_PARALELO(
	IdValor		INT IDENTITY(1,1) NOT NULL,
	Valor		NUMERIC(7,3) NOT NULL CHECK(Valor > 0),
	Fecha		DATE NOT NULL,
	Habilitado	BIT DEFAULT 1 NOT NULL,
	CreatedAt	SMALLDATETIME NOT NULL DEFAULT GETDATE(),
	CONSTRAINT PK_ValorDolar PRIMARY KEY(IdValor)
)
GO
IF OBJECT_ID('dbo.USP_INSERT_VALOR_DOLAR') is not null drop procedure USP_INSERT_VALOR_DOLAR
go
CREATE PROCEDURE USP_INSERT_VALOR_DOLAR(
	@Valor NUMERIC(7,3),
	@Fecha DATE
)
AS BEGIN
	IF NOT EXISTS (SELECT * FROM dbo.VALOR_DOLAR_PARALELO WHERE Fecha = @Fecha AND Habilitado = 1) BEGIN
		INSERT dbo.VALOR_DOLAR_PARALELO(Valor, Fecha)
		VALUES(@Valor, @Fecha)
	END
	ELSE
		BEGIN
			RAISERROR('Ya existe un valor para el dolar, en la fecha %s .', 16,1)
			--CORREGIR RAISE ERROR NO FUNCIONA EL COMENTADO
			--RAISERROR('Ya existe un valor para el dolar, en la fecha %s .', 16,1,convert(NVARCHAR(10),getdate()))
		END
END
GO
IF OBJECT_ID('dbo.USP_GET_VALOR_DOLAR',N'P') IS NOT NULL
	DROP PROCEDURE dbo.USP_GET_VALOR_DOLAR
GO
CREATE PROCEDURE dbo.USP_GET_VALOR_DOLAR(
	@Fecha	DATE
)
AS BEGIN
	SELECT IdValor, Valor, Fecha, CreatedAt FROM dbo.VALOR_DOLAR_PARALELO
	WHERE Fecha = @Fecha AND Habilitado = 1
END
GO
IF OBJECT_ID('dbo.USP_GET_VALORES_DOLAR',N'P') IS NOT NULL
	DROP PROCEDURE dbo.USP_GET_VALORES_DOLAR
GO
CREATE PROCEDURE dbo.USP_GET_VALORES_DOLAR (
	@FechaInicio	DATE,
	@FechaFin		DATE,
	@Habilitado		INT
)
AS BEGIN
	SELECT IdValor, Valor, Fecha, CreatedAt FROM dbo.VALOR_DOLAR_PARALELO
	WHERE Fecha BETWEEN @FechaInicio AND @FechaFin AND Habilitado = ISNULL(@Habilitado, Habilitado)
END