use pruebas_node

IF OBJECT_ID('dbo.PERMISO_CONTROL_DETALLE_ROL_USUARIO') IS NOT NULL
	DROP TABLE dbo.PERMISO_CONTROL_DETALLE_ROL_USUARIO

IF OBJECT_ID('dbo.PERMISO_CONTROL_ROL_USUARIO') IS NOT NULL
	DROP TABLE dbo.PERMISO_CONTROL_ROL_USUARIO

CREATE TABLE dbo.PERMISO_CONTROL_ROL_USUARIO (
	
	IdPermisoControl INT IDENTITY(1,1)
	, IdOperacion INT NOT NULL
	, Descripcion VARCHAR(300) 
	, Habilitado BIT NOT NULL DEFAULT 1
	, Modulo VARCHAR(300) NOT NULL
	, FechaRegistro DATETIME NOT NULL DEFAULT GETDATE()
	, FechaActualiza DATETIME NULL

	CONSTRAINT pk_PermisoControl PRIMARY KEY (IdPermisoControl)
	
)


--OPERACIONES DEL MODULO DE PRODUCTO
INSERT INTO dbo.PERMISO_CONTROL_ROL_USUARIO(IdOperacion,Descripcion,Modulo)
VALUES(1,'Agregar un producto','PRODUCTO')
INSERT INTO dbo.PERMISO_CONTROL_ROL_USUARIO(IdOperacion,Descripcion,Modulo)
VALUES(2,'Editar un producto','PRODUCTO')


CREATE TABLE dbo.PERMISO_CONTROL_DETALLE_ROL_USUARIO (
	IdPermisoControlDetalle INT IDENTITY(1,1)
	, IdPermisoControl INT NOT NULL
	, IdRol INT NOT NULL
	, Habilitado BIT NOT NULL DEFAULT 1
	, FechaRegistro DATETIME NOT NULL DEFAULT GETDATE()
	, FechaActualiza DATETIME NULL

	CONSTRAINT PK_idPermisoControlDetalle PRIMARY KEY (IdPermisoControlDetalle)
	, CONSTRAINT FK_PermisoControlDetalle FOREIGN KEY(IdPermisoControl) REFERENCES PERMISO_CONTROL_ROL_USUARIO(IdPermisoControl)
	, CONSTRAINT FK_RolPermisoControl FOREIGN KEY(IdRol) REFERENCES ROL_USUARIO(IdRol)
)


INSERT INTO dbo.PERMISO_CONTROL_DETALLE_ROL_USUARIO(IdPermisoControl,IdRol)
VALUES(1,1)
INSERT INTO dbo.PERMISO_CONTROL_DETALLE_ROL_USUARIO(IdPermisoControl,IdRol)
VALUES(1,1)
INSERT INTO dbo.PERMISO_CONTROL_DETALLE_ROL_USUARIO(IdPermisoControl,IdRol)
VALUES(2,1)

--INSERT INTO ROL_USUARIO(NombreRol,DescripcionRol,Habilitado,CreateAt)
--VALUES('Mesero','Descripcion',1,GETDATE())


GO

IF OBJECT_ID('dbo.OBTENER_PERMISOS_CONTROLES') IS NOT NULL
	DROP PROCEDURE dbo.OBTENER_PERMISOS_CONTROLES
GO

CREATE PROCEDURE dbo.OBTENER_PERMISOS_CONTROLES(
	@IdRol INT
	, @Modulo VARCHAR(300)
)
AS BEGIN

	IF OBJECT_ID('tempdb..#TMP_PERMISOS_MODULO') IS NOT NULL
		DROP TABLE #TMP_PERMISOS_MODULO
	
	SELECT	M.IdPermisoControl
			, M.IdOperacion
			, M.Habilitado
			, M.Descripcion
			, M.Modulo
			, M.FechaRegistro
			, Procesado = 0
			, Permitir = 0
	INTO	#TMP_PERMISOS_MODULO
	FROM	dbo.PERMISO_CONTROL_ROL_USUARIO M
	WHERE	M.Habilitado = 1
			AND M.Modulo =  @Modulo

	DECLARE @IdPermisoControl INT

	WHILE (SELECT COUNT(*) FROM #TMP_PERMISOS_MODULO WHERE Procesado = 0) > 0
	BEGIN
	
		SELECT TOP 1 @IdPermisoControl = IdPermisoControl FROM #TMP_PERMISOS_MODULO WHERE Procesado = 0

		UPDATE	#TMP_PERMISOS_MODULO
		SET		Procesado = 1
				, Permitir = CASE WHEN EXISTS (	SELECT  DET.IdRol
												FROM	dbo.PERMISO_CONTROL_DETALLE_ROL_USUARIO DET
														INNER JOIN dbo.ROL_USUARIO ROL
															ON DET.IdRol = ROL.IdRol
												WHERE	DET.Habilitado = 1
														AND DET.IdRol = @IdRol
														AND DET.IdPermisoControl = @IdPermisoControl
												) THEN 1 ELSE 0 END

		WHERE	IdPermisoControl = @IdPermisoControl

	END

	SELECT	IdOperacion
			, Permitir
			, Descripcion
			, Modulo
			, FechaRegistro		
	FROM	#TMP_PERMISOS_MODULO

END

GO
--EJEMPLO DE EJECUCION 
EXEC OBTENER_PERMISOS_CONTROLES 1,'PRODUCTO'